pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:teamgahsp/gahsp.git
          - cd gahsp.git
          - git push --mirror git@github.com:teamgahsp/gahsp.git